Issue 112
Amal-Mathew204/game-development-unity-project pull request #116
Opened 2024-12-21 21:03 UTC by Zahid2104

This issue adds the setting UI within the main menu which can be accessed by the user by selecting the settings button. Within this UI users can change settings to thier personal prefereneces such as ability to change NPC Subtitle speed, Camera sensetivity, SFX sound and music sounds. The issue also adds a tutorial screen which can be selected when the user clicks on the tutorial button within the main menu providing them with information such as the aim of the game and instructions on how to play the game. In addition the issue also adds a new load game button which is yet to be implemented and a few design changes such as new button colours and borders and a background image 

Closes #112 
Closes #18

2024-12-21 22:19 UTC, Amal-Mathew204 requested changes

2024-12-21 22:19 UTC, Amal-Mathew204 commented on Assets/Scripts/Menu/TutorialMenuScript.cs
> +    }
add summaries to these methods

2024-12-21 22:19 UTC, Amal-Mathew204 commented on Assets/Scripts/Menu/OptionMenuScript.cs
> +{
The File is named menu so the namespace should be `Scripts.Menu`

2024-12-21 22:19 UTC, Amal-Mathew204 commented on Assets/TutorialMenu.uss
Should be place the USS files in a MenuStyles folder?

2024-12-22 20:40 UTC, Aylinx13 requested changes
1.  You're awarded microchips not tokens. 
2.  Mention controls for walking
3. Mention controls for camera
4. Mention controls for pause menu
5. Mention controls for accepting tasks (f key)
6. Mention the enter key for the start npc
7. Change the description of the m key to be for the active mission log
8. Mention you have to stop and look at the item to pick it up

2024-12-22 20:45 UTC, Amal-Mathew204 commented
Background Images for this Main Menu should be placed in an styles folder specific to the main menu

2024-12-26 23:20 UTC, Amal-Mathew204 approved these changes

2024-12-26 23:22 UTC, Amal-Mathew204 approved these changes

2024-12-27 11:43 UTC, Aylinx13 approved these changes

2024-12-27 11:51 UTC, merged